{{- if hasKey .Values "secret" }}
{{- $root := .Values.secret }}
{{- $releaseName := .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.app }}-env-secret
  labels:
    app: {{ $.Values.app }}
    chart: {{ template "merge.chart" $ }}
    release: {{ $releaseName }}
type: Opaque
stringData:
{{- range $k,$v := $root }}
  {{$k }}: {{ default "" $v | quote }}
{{- end}}
{{- end}}
